name: better_shutdown
description: "Shutdown app for windows"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '3.22.2'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  collection: 1.18.0
  intl: 0.19.0
  flutter_launcher_icons: 0.13.1
  provider: 6.1.2
  window_manager: 0.3.8
  material_symbols_icons: 4.2762.0
  url_launcher: 6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "windows/runner/resources/icon.png"
  windows:
    generate: true
    image_path: "windows/runner/resources/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
