name: better_shutdown
description: "Shutdown app for windows"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '3.19.2'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  window_manager: 0.3.8
  intl: 0.19.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
